trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreInstaller@0
  displayName: install .NET Core SDK
  inputs:
    packageType: sdk
    version: 2.2.203
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
