trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  lfs: true
- task: UseDotNet@2
  displayName: install .NET Core SDK
  inputs:
    packageType: sdk
    version: 3.1.300
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
