version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.103-sdk
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
      - run: apt-get install git-lfs
      - checkout
      - run: pwd
      - run: dotnet restore
      - run: dotnet build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
