version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1.300
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
      - run: apt-get install git-lfs
      - checkout
      - run: pwd
      - run: dotnet restore
      - run: dotnet tool install -g BomSweeper.GlobalTool
      - run: /root/.dotnet/tools/bomsweeper '**/*.cs' '**/*.csproj' '**/*.sln'
      - run: dotnet build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
